"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$terraform\
$nodejs\
$rust\
$golang\
$php\
$time\
\n$character"""

[directory]
style = "fg:#e3e5e5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#394260"
symbol = ""
format = '[[ $symbol $branch ](fg:#769ff0)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0)]($style)'

[lua]
symbol = "🌕"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:#212736"
format = '[[ $symbol$workspace ($version) ](fg:#769ff0)]($style)'
detect_extensions = ["tf", "tfvars", "hcl"]
detect_files = [".terraform-version"]
detect_folders = [".terraform"]

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[php]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb)]($style)'
