"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$git_branch\
$git_status\
$fill\
$lua\
$terraform\
$nodejs\
$rust\
$golang\
\n$character"""

[directory]
style = "fg:#e3e5e5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#394260"
symbol = ""
format = '[[ $symbol $branch ](fg:#7aa2f7)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#f7768e)]($style)'

[lua]
symbol = "🌕"
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ff899d)]($style)'

[terraform]
symbol = "󱁢 "
style = "bg:#212736"
format = '[[ $symbol$workspace ($version) ](fg:#ff899d)]($style)'
detect_extensions = ["tf", "tfvars", "hcl"]
detect_files = [".terraform-version"]
detect_folders = [".terraform"]

[nodejs]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ff899d)]($style)'

[rust]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ff899d)]($style)'

[golang]
symbol = ""
style = "bg:#212736"
format = '[[ $symbol ($version) ](fg:#ff899d)]($style)'

# [time]
# disabled = false
# time_format = "%R" # Hour:Minute Format
# style = "bg:#1d2230"
# format = '[[  $time ](fg:#a0a9cb)]($style)'
