#!/bin/bash

# A CV cover letter generator for the Norwegian language

# function to prompt the user for a filename
get_filename() {
	read -p "Employer name: " filename
	echo "$filename"
}

# function to create and open a file in the specified directory
open_file() {

	# Cd into the directory
	cd "$1" || exit

	# Create the file in the specified directory
	touch "$1/cl-$filename.tex"
	touch "$1/cl-$filename-content.tex"

	# create unique identifier and links section
	timestamp="$(date +"%Y%m%d%H%M")"

	# format the files
	{
    echo "\documentclass[11pt,a4paper]{moderncv}"
    echo "\moderncvtheme[red]{classic}"
    echo -en "\n"
    echo "\usepackage[utf8]{inputenc}"
    echo -en "\n"
    echo "\usepackage[scale=0.8]{geometry}"
    echo "\recomputelengths"
    echo -en "\n"
    echo "\firstname{Fornavn}"
    echo "\familyname{Etternavn}"
    echo "\title{Seniorkonsulent}"
    echo "\address{Adresse}{Postnr Sted}"
    echo "\mobile{+47 12345678}"
    echo "\email{adresse@domene.com}"
    echo "\social[twitter]{@kontonavn}"
    echo "\social[github]{https://github.com/kontonavn}"
    echo "\photo[64pt][0pt]{"./portrett.jpg"}"
    echo -en "\n"
    echo "\begin{document}"
    echo "\recipient{[Rekrutterer]}{Firmanavn\\\Adresse\\\Postnr Poststed}"
    echo "\date{04.04.2024}"
    echo "\opening{Hei [Rekrutterer],}"
    echo "\closing{Med Vennlig hilsen,}"
    echo -en "\n"
    echo "% Hent søknadstekst fra egen fil"
    echo "\makelettertitle"
    echo "\input{cl-$filename-content}"
    echo -en "\n"
    echo -en "\n"
    echo -en "\n"
    echo "\makeletterclosing"
    echo "%\clearpage\end{CJK*}" 
    echo -en "\n"
    echo "\end{document}"
	} >>"$1/cl-$filename.tex"

  {
    echo "% Skriv søknadsteksten her. Tips: Les stillingsannonsen godt. Bruk gjerne ChatGPT som hjelpemiddel"
    echo "eksempeltekst"
  } >>"$1/cl-$filename-content.tex"

	# Open the file in Neovim
	nvim '+ normal ggzzi' -O "$1/cl-$filename.tex" "$1/cl-$filename-content.tex"
}

# Prompt the user if no filename is provided
if [[ $# -eq 0 ]]; then
	filename=$(get_filename)
fi

# if more than one argument is given, print error message and stop script
if [[ $# -gt 1 ]]; then
	echo "Please provide only one filename separated by dashes, without .tex extension."
	echo "Example: mkcl employername"
	exit 1
fi

# set filename to the argument given to the script
if [[ $# -eq 1 ]]; then
	filename=$1
fi

open_file "$MODERNCV"
